// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace e2e.Model;

public partial class Area
{
    public Guid AreaId { get; set; }

    public string AreaName { get; set; }

    public string AreaDescription { get; set; }
}