// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace e2e.Model;

public partial class CampaignStatus
{
    public Guid CampaignStatusId { get; set; }

    public string CampaignStatusName { get; set; }

    public string CampaignStatusDescription { get; set; }

    public virtual ICollection<Campaign> Campaigns { get; set; } = new List<Campaign>();
}