// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace e2e.Model;

[Keyless]
public partial class MasterDocument
{
    public Guid CampaignId { get; set; }

    public string DocumentStatus { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual ICollection<ParticipantDetail> ParticipantDetails { get; set; } = new List<ParticipantDetail>();
}