// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace e2e.Model;

public partial class ParticipantDetail
{
    public Guid DetailId { get; set; }

    public Guid CampaignId { get; set; }

    public string ParticipantName { get; set; }

    public string ParticipantSectionName { get; set; }

    public string AreaName { get; set; }

    public string TitleName { get; set; }

    public string FieldValue { get; set; }

    public string FieldType { get; set; }

    public virtual MasterDocument Campaign { get; set; }
}