// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace e2e.Model;

public partial class ProductsService
{
    public Guid ProductServiceId { get; set; }

    public string ProductServiceName { get; set; }

    public string ProductServiceDescription { get; set; }

    public virtual ICollection<Campaign> Campaigns { get; set; } = new List<Campaign>();
}