// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace e2e.Model;

public partial class Profile
{
    public Guid ProfileId { get; set; }

    public string ProfileName { get; set; }

    public string ProfileDescription { get; set; }
}